version: '3.8'

services:
  web:
    build: .
    image: audio-sentiment-analysis:latest
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://william:Al12N%23assr@sentimentAnalysis-mysql/sentimentAnalysis
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Al12N%23assr
      - MYSQL_DATABASE=sentimentAnalysis
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Al12N%23assr