version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynet
    volumes:
      - uploaded_audio:/app/uploaded_audio
      - ./${GCP_CREDENTIALS_FILE}:/app/${GCP_CREDENTIALS_FILE}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/${GCP_CREDENTIALS_FILE}
  db:
    image: postgres:16
    container_name: sentimentanalysis-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet
    restart: always

networks:
  mynet:
    driver: bridge

volumes:
  postgres_data:
  uploaded_audio: