version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynet
    volumes:
      - uploaded_audio:/app/uploaded_audio
      - ./gcp.json:/app/gcp.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp.json
  db:
    image: postgres:16
    container_name: sentimentanalysis-db
    environment:
      POSTGRES_DB: sentimentanalysis_db
      POSTGRES_USER: william
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet
    restart: always

networks:
  mynet:
    driver: bridge

volumes:
  postgres_data:
  uploaded_audio:
